-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Fruit Here" --Put The Fruit You Want Here (Fire, Ice, Light, Rumble, Invisible, String, Paw, String, Dark)
}

game:GetService("ReplicatedStorage").Remote.Fruit:FireServer(unpack(args))
